//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APOFASI_PARAMETERS
    {
        public int ΚΩΔΙΚΟΣ { get; set; }
        public Nullable<int> ΣΧΟΛΗ_ΕΙΔΟΣ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΥΠΟΥΡΓΟΣ { get; set; }
        public string ΕΓΚΥΚΛΙΟΣ_ΔΙΟΙΚΗΣΗ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΔΣ { get; set; }
        public string ΑΠΟΦΑΣΕΙΣ_ΔΣ { get; set; }
        public string ΚΑΕ { get; set; }
    }
}
