//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dupl_STUDENT_DATA
    {
        public int ΜΑΘΗΤΗΣ_ΚΩΔΙΚΟΣ { get; set; }
        public Nullable<int> ΣΧΟΛΗ { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string ΑΦΜ { get; set; }
        public string ΕΠΩΝΥΜΟ { get; set; }
        public string ΟΝΟΜΑ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
        public string ΑΔΤ { get; set; }
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
    }
}
