//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrimusDBEntities : DbContext
    {
        public PrimusDBEntities()
            : base("name=PrimusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APOFASI_PARAMETERS> APOFASI_PARAMETERS { get; set; }
        public virtual DbSet<USER_ADMINS> USER_ADMINS { get; set; }
        public virtual DbSet<USER_SCHOOLS> USER_SCHOOLS { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΗ_ΣΙΤΙΣΗ> ΑΠΟΦΑΣΗ_ΣΙΤΙΣΗ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΗ_ΣΤΕΓΑΣΗ> ΑΠΟΦΑΣΗ_ΣΤΕΓΑΣΗ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΗ_ΣΥΝΕΧΕΙΑ> ΑΠΟΦΑΣΗ_ΣΥΝΕΧΕΙΑ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΗ_ΧΟΡΗΓΗΣΗ> ΑΠΟΦΑΣΗ_ΧΟΡΗΓΗΣΗ { get; set; }
        public virtual DbSet<Δ_ΑΝΤΙΠΡΟΕΔΡΟΙ> Δ_ΑΝΤΙΠΡΟΕΔΡΟΙ { get; set; }
        public virtual DbSet<Δ_ΔΙΑΧΕΙΡΙΣΤΕΣ> Δ_ΔΙΑΧΕΙΡΙΣΤΕΣ { get; set; }
        public virtual DbSet<Δ_ΔΙΕΥΘΥΝΤΕΣ> Δ_ΔΙΕΥΘΥΝΤΕΣ { get; set; }
        public virtual DbSet<Δ_ΔΙΕΥΘΥΝΤΕΣ_ΓΕΝΙΚΟΙ> Δ_ΔΙΕΥΘΥΝΤΕΣ_ΓΕΝΙΚΟΙ { get; set; }
        public virtual DbSet<Δ_ΔΙΟΙΚΗΤΕΣ> Δ_ΔΙΟΙΚΗΤΕΣ { get; set; }
        public virtual DbSet<Δ_ΠΡΟΙΣΤΑΜΕΝΟΙ> Δ_ΠΡΟΙΣΤΑΜΕΝΟΙ { get; set; }
        public virtual DbSet<ΕΙΔΙΚΟΤΗΤΕΣ> ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
        public virtual DbSet<ΕΠΙΔΟΜΑ_ΣΙΤΙΣΗ> ΕΠΙΔΟΜΑ_ΣΙΤΙΣΗ { get; set; }
        public virtual DbSet<ΕΠΙΔΟΜΑ_ΣΤΕΓΑΣΗ> ΕΠΙΔΟΜΑ_ΣΤΕΓΑΣΗ { get; set; }
        public virtual DbSet<ΕΠΙΔΟΜΑ_ΣΥΝΕΧΕΙΑ> ΕΠΙΔΟΜΑ_ΣΥΝΕΧΕΙΑ { get; set; }
        public virtual DbSet<ΕΠΙΔΟΜΑ_ΧΟΡΗΓΗΣΗ> ΕΠΙΔΟΜΑ_ΧΟΡΗΓΗΣΗ { get; set; }
        public virtual DbSet<ΕΠΙΔΟΤΗΣΕΙΣ_ΠΟΣΑ> ΕΠΙΔΟΤΗΣΕΙΣ_ΠΟΣΑ { get; set; }
        public virtual DbSet<ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ> ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
        public virtual DbSet<ΚΟΙΝΩΝΙΚΑ_ΚΡΙΤΗΡΙΑ> ΚΟΙΝΩΝΙΚΑ_ΚΡΙΤΗΡΙΑ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΗΣ> ΜΑΘΗΤΗΣ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ> ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ { get; set; }
        public virtual DbSet<ΣΥΣ_ΑΞΙΟΛΟΓΗΣΗ> ΣΥΣ_ΑΞΙΟΛΟΓΗΣΗ { get; set; }
        public virtual DbSet<ΣΥΣ_ΑΠΟΡΡΙΨΗ_ΑΙΤΙΑ> ΣΥΣ_ΑΠΟΡΡΙΨΗ_ΑΙΤΙΑ { get; set; }
        public virtual DbSet<ΣΥΣ_ΔΗΜΟΣ> ΣΥΣ_ΔΗΜΟΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΓΓΡΑΦΑ_ΕΙΔΗ> ΣΥΣ_ΕΓΓΡΑΦΑ_ΕΙΔΗ { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΠΙΔΟΜΑΤΑ> ΣΥΣ_ΕΠΙΔΟΜΑΤΑ { get; set; }
        public virtual DbSet<ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΕΣ> ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΕΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΗ_ΕΝΟΤΗΤΑ> ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΗ_ΕΝΟΤΗΤΑ { get; set; }
        public virtual DbSet<ΣΥΣ_ΣΧΟΛΕΣ_ΕΙΔΗ> ΣΥΣ_ΣΧΟΛΕΣ_ΕΙΔΗ { get; set; }
        public virtual DbSet<ΣΥΣ_ΣΧΟΛΙΚΑ_ΕΤΗ> ΣΥΣ_ΣΧΟΛΙΚΑ_ΕΤΗ { get; set; }
        public virtual DbSet<ΣΥΣ_ΣΧΟΛΙΚΕΣ_ΔΟΜΕΣ> ΣΥΣ_ΣΧΟΛΙΚΕΣ_ΔΟΜΕΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΤΑΞΕΙΣ> ΣΥΣ_ΤΑΞΕΙΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΦΥΛΑ> ΣΥΣ_ΦΥΛΑ { get; set; }
        public virtual DbSet<sqlUSER_SCHOOL> sqlUSER_SCHOOL { get; set; }
        public virtual DbSet<ΣΥΣ_ΣΧΟΛΕΣ> ΣΥΣ_ΣΧΟΛΕΣ { get; set; }
        public virtual DbSet<ΕΙΔΙΚΟΤΗΤΕΣ_ΕΤΟΣ_ΣΧΟΛΗ> ΕΙΔΙΚΟΤΗΤΕΣ_ΕΤΟΣ_ΣΧΟΛΗ { get; set; }
        public virtual DbSet<ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑ> ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public virtual DbSet<qrySTUDENT_SELECTOR> qrySTUDENT_SELECTOR { get; set; }
        public virtual DbSet<qrySTUDENT_INFO> qrySTUDENT_INFO { get; set; }
        public virtual DbSet<ΜΑΘΗΤΗΣ_ΚΟΙΝΩΝΙΚΑ> ΜΑΘΗΤΗΣ_ΚΟΙΝΩΝΙΚΑ { get; set; }
        public virtual DbSet<sqlSTUDENT_INFO> sqlSTUDENT_INFO { get; set; }
        public virtual DbSet<sqlSTUDENT_AITISEIS> sqlSTUDENT_AITISEIS { get; set; }
        public virtual DbSet<sqlΑΙΤΗΣΕΙΣ_ΑΠΟΡΡΙΨΗ> sqlΑΙΤΗΣΕΙΣ_ΑΠΟΡΡΙΨΗ { get; set; }
        public virtual DbSet<sqlΑΙΤΗΣΕΙΣ_ΕΓΚΡΙΣΗ> sqlΑΙΤΗΣΕΙΣ_ΕΓΚΡΙΣΗ { get; set; }
        public virtual DbSet<sqlΑΙΤΗΣΕΙΣ_ΕΚΚΡΕΜΕΙΣ> sqlΑΙΤΗΣΕΙΣ_ΕΚΚΡΕΜΕΙΣ { get; set; }
        public virtual DbSet<sqlΑΙΤΗΣΕΙΣ_ΜΗΤΡΩΟ> sqlΑΙΤΗΣΕΙΣ_ΜΗΤΡΩΟ { get; set; }
        public virtual DbSet<sqlΑΙΤΗΣΕΙΣ_ΕΠΙΣΥΝΑΨΗ> sqlΑΙΤΗΣΕΙΣ_ΕΠΙΣΥΝΑΨΗ { get; set; }
        public virtual DbSet<sumΕΠΙΔΟΜΑ_ΧΟΡΗΓΗΣΗ> sumΕΠΙΔΟΜΑ_ΧΟΡΗΓΗΣΗ { get; set; }
        public virtual DbSet<sumΕΠΙΔΟΜΑ_ΣΥΝΕΧΕΙΑ> sumΕΠΙΔΟΜΑ_ΣΥΝΕΧΕΙΑ { get; set; }
        public virtual DbSet<sumΕΠΙΔΟΜΑ_ΣΙΤΙΣΗ> sumΕΠΙΔΟΜΑ_ΣΙΤΙΣΗ { get; set; }
        public virtual DbSet<sumΕΠΙΔΟΜΑ_ΣΤΕΓΑΣΗ> sumΕΠΙΔΟΜΑ_ΣΤΕΓΑΣΗ { get; set; }
        public virtual DbSet<sqlΑΠΟΦΑΣΕΙΣ_ΜΗΤΡΩΟ> sqlΑΠΟΦΑΣΕΙΣ_ΜΗΤΡΩΟ { get; set; }
        public virtual DbSet<sqlΕΠΙΔΟΜΑ_ΜΗΤΡΩΟ> sqlΕΠΙΔΟΜΑ_ΜΗΤΡΩΟ { get; set; }
        public virtual DbSet<sqlEPIDOMA_ALL_DETAIL> sqlEPIDOMA_ALL_DETAIL { get; set; }
        public virtual DbSet<sqlEPIDOMA_SITISI> sqlEPIDOMA_SITISI { get; set; }
        public virtual DbSet<sqlEPIDOMA_STEGASI> sqlEPIDOMA_STEGASI { get; set; }
        public virtual DbSet<sqlEPIDOMA_SYNEXEIA> sqlEPIDOMA_SYNEXEIA { get; set; }
        public virtual DbSet<sqlEPIDOMA_XORIGISI> sqlEPIDOMA_XORIGISI { get; set; }
        public virtual DbSet<sqlSUM_EPIDOMA_ALLTYPES> sqlSUM_EPIDOMA_ALLTYPES { get; set; }
        public virtual DbSet<sqlSUM_EPIDOMA_DETAIL> sqlSUM_EPIDOMA_DETAIL { get; set; }
        public virtual DbSet<sqlSUM_EPIDOMA_YEAR> sqlSUM_EPIDOMA_YEAR { get; set; }
        public virtual DbSet<APOFASI_PARAMETERS2> APOFASI_PARAMETERS2 { get; set; }
        public virtual DbSet<ΕΠΙΔΟΜΑ_ΣΙΤΙΣΗ2> ΕΠΙΔΟΜΑ_ΣΙΤΙΣΗ2 { get; set; }
        public virtual DbSet<ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ2> ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ2 { get; set; }
        public virtual DbSet<ΣΥΣ_ΜΗΝΕΣ> ΣΥΣ_ΜΗΝΕΣ { get; set; }
        public virtual DbSet<sqlEPIDOMA_SITISI2> sqlEPIDOMA_SITISI2 { get; set; }
        public virtual DbSet<sqlΑΙΤΗΣΕΙΣ2_ΕΠΙΣΥΝΑΨΗ> sqlΑΙΤΗΣΕΙΣ2_ΕΠΙΣΥΝΑΨΗ { get; set; }
        public virtual DbSet<sumΕΠΙΔΟΜΑ_ΣΙΤΙΣΗ2_ΜΗΝΑΣ> sumΕΠΙΔΟΜΑ_ΣΙΤΙΣΗ2_ΜΗΝΑΣ { get; set; }
        public virtual DbSet<ΜΑΘΗΤΗΣ_ΚΟΙΝΩΝΙΚΑ2> ΜΑΘΗΤΗΣ_ΚΟΙΝΩΝΙΚΑ2 { get; set; }
        public virtual DbSet<sqlSTUDENT_AITISEIS2> sqlSTUDENT_AITISEIS2 { get; set; }
        public virtual DbSet<sqlSTUDENT_INFO2> sqlSTUDENT_INFO2 { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΤΗ> ΣΥΣ_ΕΤΗ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΗ_ΣΙΤΙΣΗ2> ΑΠΟΦΑΣΗ_ΣΙΤΙΣΗ2 { get; set; }
        public virtual DbSet<APP_STATUS> APP_STATUS { get; set; }
        public virtual DbSet<SYS_LOGINS> SYS_LOGINS { get; set; }
        public virtual DbSet<sqlSCHOOL_LOGINS> sqlSCHOOL_LOGINS { get; set; }
        public virtual DbSet<dupl_STUDENT_DATA> dupl_STUDENT_DATA { get; set; }
        public virtual DbSet<UPLOADS> UPLOADS { get; set; }
        public virtual DbSet<UPLOADS_FILES> UPLOADS_FILES { get; set; }
    }
}
