//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qrySTUDENT_INFO
    {
        public int ΜΑΘΗΤΗΣ_ΚΩΔΙΚΟΣ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΣΧΟΛΗ { get; set; }
        public string ΣΧΟΛΗ_ΤΥΠΟΣ { get; set; }
    }
}
