//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlSTUDENT_AITISEIS
    {
        public int ΜΑΘΗΤΗΣ_ΚΩΔΙΚΟΣ { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string ΑΦΜ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΤΑΞΗ_ΛΕΚΤΙΚΟ { get; set; }
        public string SCHOOLYEAR_TEXT { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΑΙΤΗΣΗ { get; set; }
        public Nullable<int> ΣΧΟΛΗ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public int ΑΙΤΗΣΗ_ΚΩΔ { get; set; }
        public string ΕΠΙΔΟΜΑ_ΚΕΙΜΕΝΟ { get; set; }
        public string ΣΥΝΕΧΕΙΑ { get; set; }
        public Nullable<int> ΗΛΙΚΙΑ { get; set; }
        public Nullable<decimal> ΟΙΚΟΓΕΝΕΙΑ_ΕΙΣΟΔΗΜΑ { get; set; }
        public Nullable<decimal> ΜΙΣΘΩΤΗΡΙΟ_ΠΟΣΟ { get; set; }
        public Nullable<System.DateTime> ΜΙΣΘΩΤΗΡΙΟ_ΗΜΝΙΑ { get; set; }
        public string ΚΟΙΝΩΝΙΚΗ_ΟΜΑΔΑ { get; set; }
        public Nullable<decimal> ΣΙΤΙΣΗ_ΠΟΣΟ { get; set; }
        public Nullable<decimal> ΣΤΕΓΑΣΗ_ΠΟΣΟ { get; set; }
    }
}
