//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlSTUDENT_INFO2
    {
        public int ΜΑΘΗΤΗΣ_ΚΩΔΙΚΟΣ { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string ΑΦΜ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΓΕΝΝΗΣΗ { get; set; }
        public string GENDER { get; set; }
        public string ΚΑΤΟΙΚΙΑ_ΔΗΜΟΣ { get; set; }
        public string ΚΑΤΟΙΚΙΑ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public string ΚΑΤΟΙΚΙΑ_ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΚΑΤΟΙΚΙΑ_ΠΕΡΙΟΧΗ { get; set; }
        public string ΔΙΑΜΟΝΗ_ΔΗΜΟΣ { get; set; }
        public string ΔΙΑΜΟΝΗ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public string ΔΙΑΜΟΝΗ_ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΔΙΑΜΟΝΗ_ΠΕΡΙΟΧΗ { get; set; }
        public string ΚΑΤΟΙΚΙΑ_ΤΗΛΕΦΩΝΟ { get; set; }
        public string ΔΙΑΜΟΝΗ_ΤΗΛΕΦΩΝΟ { get; set; }
        public string ΠΑΡΑΤΗΡΗΣΕΙΣ { get; set; }
        public Nullable<int> ΣΧΟΛΗ { get; set; }
    }
}
