//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlΕΠΙΔΟΜΑ_ΜΗΤΡΩΟ
    {
        public int ID { get; set; }
        public int ΕΠΙΔΟΤΗΣΗ_ΚΩΔ { get; set; }
        public string ΕΠΙΔΟΜΑ_ΚΕΙΜΕΝΟ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΕΙΔΟΣ { get; set; }
        public string SCHOOLYEAR_TEXT { get; set; }
        public string PERIFERIAKI_TEXT { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string ΜΑΘΗΤΗΣ_ΑΦΜ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string ΤΑΞΗ_ΛΕΚΤΙΚΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΑΠΟ { get; set; }
        public Nullable<decimal> ΣΤΕΓΑΣΗ_ΠΟΣΟ { get; set; }
        public Nullable<decimal> ΣΙΤΙΣΗ_ΠΟΣΟ { get; set; }
        public bool ΣΥΝΕΧΙΣΗ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΣΥΝΤΑΞΗ { get; set; }
        public Nullable<int> ΑΠΟΦΑΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΕΠΙΔΟΜΑ_ΕΙΔΟΣ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΕΙΔΙΚΟΤΗΤΑ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΤΑΞΗ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΣΧΟΛΕΙΟ { get; set; }
        public Nullable<int> AITISI_ID { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΚΩΔ { get; set; }
        public int PERIFERIAKI_ID { get; set; }
    }
}
