//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlΑΠΟΦΑΣΕΙΣ_ΜΗΤΡΩΟ
    {
        public int ID { get; set; }
        public int ΑΠΟΦΑΣΗ_ΚΩΔ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΕΙΔΟΣ { get; set; }
        public string SCHOOLYEAR_TEXT { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string PERIFERIAKI_TEXT { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΕΓΓΡΑΦΟ_ΕΙΔΟΣ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΣΥΝΤΑΞΗ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public string ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public Nullable<decimal> ΣΤΕΓΑΣΗ_ΣΥΝΟΛΟ { get; set; }
        public Nullable<decimal> ΣΙΤΙΣΗ_ΣΥΝΟΛΟ { get; set; }
        public Nullable<short> ΠΛΗΘΟΣ { get; set; }
    }
}
