//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sumΕΠΙΔΟΜΑ_ΣΥΝΕΧΕΙΑ
    {
        public int ID { get; set; }
        public Nullable<int> ΑΠΟΦΑΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΣΧΟΛΕΙΟ { get; set; }
        public Nullable<decimal> ΣΤΕΓΑΣΗ_ΣΥΝΟΛΟ { get; set; }
        public Nullable<decimal> ΣΙΤΙΣΗ_ΣΥΝΟΛΟ { get; set; }
        public Nullable<int> ΠΛΗΘΟΣ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΕΙΔΟΣ { get; set; }
    }
}
