//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOADS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UPLOADS()
        {
            this.UPLOADS_FILES = new HashSet<UPLOADS_FILES>();
        }
    
        public int UPLOAD_ID { get; set; }
        public Nullable<int> SCHOOL_ID { get; set; }
        public Nullable<int> SCHOOLYEAR_ID { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
        public string UPLOAD_NAME { get; set; }
        public string UPLOAD_SUMMARY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UPLOADS_FILES> UPLOADS_FILES { get; set; }
    }
}
