//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΑΠΟΦΑΣΗ_ΣΙΤΙΣΗ2
    {
        public int ΑΠΟΦΑΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΣΧΟΛΗ_ΤΥΠΟΣ { get; set; }
        public Nullable<int> ΣΧΟΛΗ { get; set; }
        public string ΔΙΑΧΕΙΡΙΣΤΗΣ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΥΠΟΥΡΓΟΣ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΔΙΟΙΚΗΤΗΣ { get; set; }
        public string ΕΓΚΥΚΛΙΟΙ_Α2 { get; set; }
        public string ΠΡΑΚΤΙΚΑ_ΣΧΟΛΕΙΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public string ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public bool ΣΤΟ_ΟΡΘΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ_ΟΡΘΟ { get; set; }
        public Nullable<decimal> ΣΙΤΙΣΗ_ΠΟΣΟ { get; set; }
        public Nullable<decimal> ΣΙΤΙΣΗ_ΣΥΝΟΛΟ { get; set; }
        public Nullable<short> ΠΛΗΘΟΣ { get; set; }
        public string ΠΛΗΘΟΣ_ΛΕΚΤΙΚΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΣΥΝΤΑΞΗ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΕΙΔΟΣ { get; set; }
        public Nullable<int> ΜΗΝΑΣ { get; set; }
        public string ΕΤΟΣ { get; set; }
    }
}
