//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Δ_ΔΙΕΥΘΥΝΤΕΣ_ΓΕΝΙΚΟΙ
    {
        public int ΓΕΝΙΚΟΣ_ΚΩΔ { get; set; }
        public string ΓΕΝΙΚΟΣ { get; set; }
        public Nullable<int> ΦΥΛΟ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
    }
}
