//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Δ_ΔΙΑΧΕΙΡΙΣΤΕΣ
    {
        public int ΔΙΑΧΕΙΡΙΣΤΗΣ_ΚΩΔ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ_ΠΛΗΡΕΣ { get; set; }
        public string ΤΗΛΕΦΩΝΟ { get; set; }
        public string ΦΑΞ { get; set; }
        public Nullable<int> ΦΥΛΟ { get; set; }
    }
}
