//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΕΙΔΙΚΟΤΗΤΕΣ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΕΙΔΙΚΟΤΗΤΕΣ()
        {
            this.ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ = new HashSet<ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ>();
        }
    
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<int> SCHOOL_TYPE { get; set; }
    
        public virtual ΣΥΣ_ΣΧΟΛΕΣ_ΕΙΔΗ ΣΥΣ_ΣΧΟΛΕΣ_ΕΙΔΗ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ> ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
    }
}
