//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΕΠΙΔΟΤΗΣΕΙΣ_ΠΟΣΑ
    {
        public int ΕΠΙΔΟΤΗΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<decimal> ΣΤΕΓΑΣΗ_ΜΗΝΙΑΙΟ { get; set; }
        public Nullable<decimal> ΣΙΤΙΣΗ_ΗΜΕΡΗΣΙΟ { get; set; }
        public string ΣΤΕΓΑΣΗ_ΛΕΚΤΙΚΟ { get; set; }
        public string ΣΙΤΙΣΗ_ΛΕΚΤΙΚΟ { get; set; }
        public string ΚΑΕ { get; set; }
    }
}
