//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ
    {
        public int SSE_ID { get; set; }
        public int SCHOOLYEAR_ID { get; set; }
        public int SCHOOL_ID { get; set; }
        public int EIDIKOTITA_ID { get; set; }
    
        public virtual ΕΙΔΙΚΟΤΗΤΕΣ ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
        public virtual ΣΥΣ_ΣΧΟΛΙΚΑ_ΕΤΗ ΣΥΣ_ΣΧΟΛΙΚΑ_ΕΤΗ { get; set; }
        public virtual ΣΥΣ_ΣΧΟΛΕΣ ΣΥΣ_ΣΧΟΛΕΣ { get; set; }
    }
}
