//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΜΑΘΗΤΗΣ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΜΑΘΗΤΗΣ()
        {
            this.ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ = new HashSet<ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ>();
            this.ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ2 = new HashSet<ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ2>();
        }
    
        public int ΜΑΘΗΤΗΣ_ΚΩΔΙΚΟΣ { get; set; }
        public Nullable<int> ΣΧΟΛΗ_ΤΥΠΟΣ { get; set; }
        public Nullable<int> ΣΧΟΛΗ { get; set; }
        public Nullable<int> ΜΑΘΗΤΗΣ_ΑΜ { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ { get; set; }
        public string ΕΠΩΝΥΜΟ { get; set; }
        public string ΟΝΟΜΑ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
        public string ΑΜΚΑ { get; set; }
        public string ΑΦΜ { get; set; }
        public string ΑΔΤ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΓΕΝΝΗΣΗ { get; set; }
        public Nullable<int> ΦΥΛΟ { get; set; }
        public Nullable<int> ΚΑΤΟΙΚΙΑ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public Nullable<int> ΚΑΤΟΙΚΙΑ_ΔΗΜΟΣ { get; set; }
        public string ΚΑΤΟΙΚΙΑ_ΠΕΡΙΟΧΗ { get; set; }
        public string ΚΑΤΟΙΚΙΑ_ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ΔΙΑΜΟΝΗ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public Nullable<int> ΔΙΑΜΟΝΗ_ΔΗΜΟΣ { get; set; }
        public string ΔΙΑΜΟΝΗ_ΠΕΡΙΟΧΗ { get; set; }
        public string ΔΙΑΜΟΝΗ_ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΔΙΑΜΟΝΗ_ΤΗΛΕΦΩΝΑ { get; set; }
        public string ΠΑΡΑΤΗΡΗΣΕΙΣ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ> ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ2> ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ2 { get; set; }
    }
}
