//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΜΑΘΗΤΗΣ_ΚΟΙΝΩΝΙΚΑ
    {
        public int AITISI_SOCIALID { get; set; }
        public int ΑΙΤΗΣΗ_ΚΩΔ { get; set; }
        public int ΚΡΙΤΗΡΙΟ_ΚΩΔ { get; set; }
    
        public virtual ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ ΜΑΘΗΤΗΣ_ΑΙΤΗΣΗ { get; set; }
    }
}
