//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΣΧΟΛΕΣ_ΕΙΔΗ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΣΥΣ_ΣΧΟΛΕΣ_ΕΙΔΗ()
        {
            this.ΕΙΔΙΚΟΤΗΤΕΣ = new HashSet<ΕΙΔΙΚΟΤΗΤΕΣ>();
        }
    
        public int SCHOOLTYPE_ID { get; set; }
        public string SCHOOLTYPE_TEXT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΕΙΔΙΚΟΤΗΤΕΣ> ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
    }
}
