//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΕΓΓΡΑΦΑ_ΕΙΔΗ
    {
        public int ΕΓΓΡΑΦΟ_ΕΙΔΟΣ_ΚΩΔ { get; set; }
        public string ΕΓΓΡΑΦΟ_ΕΙΔΟΣ { get; set; }
    }
}
