//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΗ_ΕΝΟΤΗΤΑ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΗ_ΕΝΟΤΗΤΑ()
        {
            this.ΣΥΣ_ΔΗΜΟΣ = new HashSet<ΣΥΣ_ΔΗΜΟΣ>();
        }
    
        public int PERIFERIA_ENOTITA_ID { get; set; }
        public string PERIFERIA_ENOTITA_NAME { get; set; }
        public Nullable<int> PERIFERIA_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΣΥΣ_ΔΗΜΟΣ> ΣΥΣ_ΔΗΜΟΣ { get; set; }
        public virtual ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑ ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
    }
}
