//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΣΧΟΛΕΣ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΣΥΣ_ΣΧΟΛΕΣ()
        {
            this.ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ = new HashSet<ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ>();
        }
    
        public int SCHOOL_ID { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string ΤΑΧ_ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string ΓΡΑΜΜΑΤΕΙΑ { get; set; }
        public string ΦΑΞ { get; set; }
        public string EMAIL { get; set; }
        public string ΔΙΕΥΘΥΝΤΗΣ { get; set; }
        public Nullable<int> ΔΙΕΥΘΥΝΤΗΣ_ΦΥΛΟ { get; set; }
        public string ΚΙΝΗΤΟ { get; set; }
        public Nullable<int> SCHOOL_TYPE { get; set; }
        public Nullable<int> ΠΕΡΙΦΕΡΕΙΑΚΗ { get; set; }
        public string ΥΠΟΔΙΕΥΘΥΝΤΗΣ { get; set; }
        public Nullable<int> ΥΠΟΔΙΕΥΘΥΝΤΗΣ_ΦΥΛΟ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ> ΕΤΗ_ΣΧΟΛΕΣ_ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
        public virtual ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΕΣ ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΕΣ { get; set; }
        public virtual ΣΥΣ_ΣΧΟΛΙΚΕΣ_ΔΟΜΕΣ ΣΥΣ_ΣΧΟΛΙΚΕΣ_ΔΟΜΕΣ { get; set; }
    }
}
